name       : db5
version    : 5.3.21
release    : 5
source     :
    - http://download.oracle.com/berkeley-db/db-5.3.21.tar.gz : ddd92a930317df92021054c03992392db9ea5cddba43bef8920d392a82114fb8
license    : BSD-3-Clause
component  : system.base
libsplit   : no
summary    : Berkeley Database v5
description: |
    This package provides different tools for manipulating databases in the Berkeley Database v5 format.
patterns   :
    - docs : /usr/share/doc
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-10140.patch
    dist/configure --prefix=/usr  \
               --enable-compat185 \
               --enable-dbm       \
               --disable-static   \
               --enable-cxx
build      : |
    %make
install    : |
    %make_install docdir=/usr/share/doc/db-$version
