name       : db5
version    : 5.3.28
release    : 9
source     :
    - http://download.oracle.com/berkeley-db/db-5.3.28.tar.gz : e0a992d740709892e81f9d93f06daf305cf73fb81b545afe72478043172c3628
license    : BSD-3-Clause
component  : system.base
libsplit   : no
emul32     : yes
summary    : Berkeley Database v5
description: |
    This package provides different tools for manipulating databases in the Berkeley Database v5 format.
patterns   :
    - docs : /usr/share/doc
    - 32bit-devel : /usr/share/doc/db-*/db5-32bit-devel
setup      : |
    %patch -p0 < $pkgfiles/atomic.patch
    dist/configure --prefix=%PREFIX% \
               --build=%HOST% \
               --libdir=%libdir% \
               --libexecdir=%libdir%/%PKGNAME% \
               --enable-compat185 \
               --enable-dbm \
               --disable-static \
               --enable-cxx
build      : |
    %make
install    : |
    %make_install docdir=/usr/share/doc/db-$version

    echo "This is a placeholder file to create the db5-32bit-devel pacakge" > $installdir/usr/share/doc/db-$version/db5-32bit-devel
