name        : db5
version     : 5.3.21
release     : 5
source      :
    - https://solus-project.com/sources/db-5.3.21.tar.gz : ddd92a930317df92021054c03992392db9ea5cddba43bef8920d392a82114fb8
license     :
    - GPLv3+
summary     : Berkeley Database v5
description : |
    This package provides different tools for manipulating databases in the Berkeley Database v5 format.
    
patterns   :
    - /usr/lib
    - docs: /usr/share/doc
setup      : |
    mkdir build && cd build
    ../dist/configure --prefix=/usr \
                      --enable-compat185 \
                      --enable-dbm \
                      --disable-static \
                      --enable-cxx
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    mkdir -p %installroot%/usr/share/doc/db5
    mv %installroot%/usr/docs/* %installroot%/usr/share/doc/db5/
    rm -r %installroot%/usr/docs
